config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get 'download', to: 'downloads#show', as: 'download'
  resources :contacts, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, :email, :message, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def create
    @contact = Contact.new(contact_params)

    if @contact.valid?
      ContactMailer.with(contact: @contact).send_contact_email.deliver_now
      redirect_to root_path
      flash.alert = ""
    else
      flash.notice = ""
      render 'pages/home', status: :unprocessable_entity
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :message)
  end
end

app/controllers/downloads_controller.rb
class DownloadsController < ApplicationController
  def show
    file_path = Rails.root.join('public','CV_Kévin_Rossi_FR.pdf')
    send_file file_path, type: 'application/octet-stream', filename: 'CV_Kévin_Rossi_FR.pdf', disposition: 'attachment'
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/create.html.erb
<h1>Contacts#create</h1>
<p>Find me in app/views/contacts/create.html.erb</p>

app/views/downloads/show.html.erb
<h1>Downloads#show</h1>
<p>Find me in app/views/downloads/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- Hotjar Tracking Code for https://www.kevinrossi.me/ -->
    <script>
        (function(h,o,t,j,a,r){
            h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
            h._hjSettings={hjid:5125820,hjsv:6};
            a=o.getElementsByTagName('head')[0];
            r=o.createElement('script');r.async=1;
            r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
            a.appendChild(r);
        })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
    </script>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render "shared/alert" %>
    <%= render 'shared/footer' %>
    <%= render "shared/top_btn" %>
  </body>
</html>

app/views/pages/_carousel.html.erb
  <div data-controller="carousel" class="card-about" id="projects_section">
    <h2>Réalisations</h2>
    <div class="carousel-container">
      <button data-action="click->carousel#previous" class="carousel-control prev-control">&lt;</button>
      <div data-carousel-target="item" class="carousel-item prev horizontal" id="portfolio">
        <%= image_tag "carousel/portfolio.png", alt: "Previous Image" %>
      </div>
      <div data-carousel-target="item" class="carousel-item active" id="bestunited">
        <%= image_tag "carousel/bestunited1.jpg", alt: "Current Image" %>
      </div>
      <div data-carousel-target="item" class="carousel-item next horizontal" id="candlesoso">
        <%= image_tag "carousel/candlesoso.png", alt: "Next Image" %>
      </div>
      <div data-carousel-target="item" class="carousel-item horizontal" id="flameshift">
        <%= image_tag "carousel/flameshift.png" %>
      </div>
      <div data-carousel-target="item" class="carousel-item horizontal" id="datefaker">
        <%= image_tag "carousel/datefaker1.png" %>
      </div>
      <button data-action="click->carousel#next" class="carousel-control next-control">&gt;</button>
    </div>
    <div class="description" data-carousel-target="description">
    </div>
  </div>

app/views/pages/home.html.erb
<div class="main-container">

<div class="banner">
  <h1><span data-controller="typed" data-typed-strings-value="<%= ["Kévin ROSSI"]%>"></span></h1>
  <h2>Développeur Fullstack</h2>
</div>

  <div class="card-about" id='about_section'>
    <h2>Qui suis-je ?</h2>
    <div class="presentation">
      <div class="paragraph">
        <p>Je m'appelle Kévin Rossi, je suis développeur web full-stack <strong>Ruby on Rails</strong> et bientôt <strong>JAVA Angular</strong>.</p>
        <p>J'ai décidé de me tourner vers le <strong>Développement Web</strong> pour me reconvertir en suivant le bootcamp chez Le Wagon Lyon car la logique et la résolution de problème en programmation sont des choses qui me passionnent.</p>
        <p>Désormais, j'ai choisi de me spécialiser sur <strong>Java et Angular</strong>, technologies au cœur des besoins actuels des entreprises et c'est pourquoi <strong>je recherche une entreprise</strong> pour m'accueillir <strong>12 mois en alternance avec OpenClassroom</strong>.</p>
        <p class="last-parag"><strong>Ingénieur mécatronique</strong> de formation, j'ai passé 3 ans et demi dans la Drôme à <strong>concevoir</strong>, construire, <strong>programmer</strong> et mettre en service des robots de contrôle non-destructif pour les centrales nucléaires.</p>
      </div>
      <%= image_tag "photo_profile.jpg", alt: "Photo profil", class: "photo" %>
    </div>
  </div>

  <div class="banner-between">
    <div class="banner-text">
      <h2>Un nouveau talent pour votre entreprise ?</h2>
      <p>Si vous avez besoin d’un développeur fullstack <strong>polyvalent</strong> pour des projets à <strong>deadlines serrées</strong>.</p>
      <p class="last-parag">Je suis le candidat qu'il vous faut, <strong>n'attendez pas</strong> pour me contacter !</p>
    </div>
  </div>

  <div class="card-about" id='presentation_section'>
    <h2>Compétences</h2>
    <div class="skills">
      <div class="assets">
        <div class="column-skill">
          <h3>Développement Web</h3>
          <ul>
            <li><i class="fa-solid fa-code"></i> Ruby on Rails, JAVA</li>
            <li><i class="fa-solid fa-wand-magic-sparkles"></i> HTML, CSS, Angular</li>
            <li><i class="fa-brands fa-js"></i> JavaScript, Stimulus</li>
            <li><i class="fa-solid fa-database"></i> PostgreSQL, SQLite</li>
            <li><i class="fa-solid fa-gear"></i> ActiveRecord, ActiveStorage</li>
          </ul>
        </div>
        <div class="column-skill">
          <h3>Outils & logiciels</h3>
          <ul>
            <li><i class="fa-brands fa-git-alt"></i> Git, GitHub</li>
            <li><i class="fa-solid fa-globe"></i> Heroku</li>
            <li><i class="fa-brands fa-figma"></i> Figma</li>
            <li><i class="fa-solid fa-list-check"></i> Trello, GanttProject</li>
            <li><i class="fa-solid fa-comment"></i> Slack, Teams</li>
          </ul>
        </div>
      </div>
      <%= link_to 'Télécharger le CV', download_path, download: 'CV_Kévin_Rossi_FR.pdf', class:"btn" %>
    </div>
  </div>

  <div class="card-about" id="contact_section">
    <h2>Contactez-moi</h2>
    <div class="form">
      <%= simple_form_for :contact, url: contacts_path, method: :post do |f| %>
          <div class="form-group">
            <%= f.input :name, label: "Nom", required: true %>
          </div>
          <div class="form-group">
            <%= f.input :email, label: "Email", required: true %>
          </div>
        <div class="form-group">
          <%= f.input :message, as: :text, label: "Message", placeholder: "Écrivez votre message ici...", required: true %>
        </div>
        <div class="form-group-btn">
          <%= f.button :submit, "Envoyer", class: "btn" %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="banner-between">
    <div class="banner-text">
      <h2>Mes atouts</h2>
      <p><strong>Curieux, touche-à-tout et déterminé</strong>, je suis une personne impliquée dans chaque projet que j'entreprends.</p>
      <p>Toujours prêt à apprendre de nouvelles choses, le défi ne m'effraie pas, il me motive.</p>
      <p><em>"Tout obstacle renforce la détermination. Celui qui s'est fixé un but n'en change pas." Léonard De Vinci</em></p>
    </div>
  </div>

  <%= render "pages/carousel" %>

  </div>
</div>

app/views/shared/_alert.html.erb
<% if flash.alert %>
  <div class="flash flash-success alert alert-dismissible fade show" role="alert">
    <span>🎉 Votre message a bien été envoyé !</span>
    <a data-bs-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>
<% end %>
<% if flash.notice %>
  <div class="flash flash-danger alert alert-dismissible fade show" role="alert">
    <span>😱 Un problème est survenu lors de l'envoi du message.</span>
    <a data-bs-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="links-social">
  <h3>Liens réseaux</h3>
      <ul>
        <div class="logo-social">
          <%= link_to "https://github.com/KevRo69", target: "_blank" do %>
            <li><i class="fa-brands fa-square-github fa-2xl"></i></li>
          <% end %>
        </div>
        <div class="logo-social">
          <%= link_to "https://www.linkedin.com/in/k%C3%A9vin-rossi-539a72150/", target: "_blank" do %>
            <li><i class="fa-brands fa-linkedin fa-2xl"></i></li>
          <% end %>
        </div>
      </ul>
    </div>
  <p>© Copyright 2024 Kévin Rossi</p>
  <p class="last-parag">Site réalisé avec Ruby on Rails</p>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <%= image_tag("avatar.jpeg", alt: "Logo", class: "avatar") %>
    <ul class="dropdown-content">
      <li><%= link_to 'Qui suis-je ?', '#about_section' %></li>
      <li><%= link_to 'Mon CV', '#presentation_section' %></li>
      <li><%= link_to 'Contact', '#contact_section' %></li>
      <li><%= link_to 'Projets', '#projects_section' %></li>
    </ul>
</div>

app/views/shared/_top_btn.html.erb
<%= link_to '#', class:"top-btn" do%>
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-6">
  <path fill-rule="evenodd" d="M12 2.25c-5.385 0-9.75 4.365-9.75 9.75s4.365 9.75 9.75 9.75 9.75-4.365 9.75-9.75S17.385 2.25 12 2.25Zm.53 5.47a.75.75 0 0 0-1.06 0l-3 3a.75.75 0 1 0 1.06 1.06l1.72-1.72v5.69a.75.75 0 0 0 1.5 0v-5.69l1.72 1.72a.75.75 0 1 0 1.06-1.06l-3-3Z" clip-rule="evenodd" />
  </svg>
<% end %>